version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: transcription-job-database
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trans_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: transcription-job-mongo
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  audio-transcription-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: audio-transcription-service
    container_name: audio-transcription-service
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data:
  mongo_data:
